<a href="https://colab.research.google.com/github/hibahrehman25-lang/ML_inter_Task1/blob/main/work/notebooks/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hibahrehman25-lang/ML_inter_Task1/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [ ]:
!git clone https://github.com/hibahrehman25-lang/ML_inter_Task1.git

fatal: destination path 'ML_inter_Task1' already exists and is not an empty directory.


In [ ]:
# ============================================================
# WEEK 8 — CAPSTONE
# Fresh Colab setup
# ============================================================

import os
import sys
import subprocess
from pathlib import Path

# ------------------------------------------------------------
# 1. Install only the packages required by this notebook
# ------------------------------------------------------------
subprocess.check_call([
    sys.executable, "-m", "pip", "install", "-q",
    "duckdb",
    "huggingface_hub",
    "scikit-learn",
    "matplotlib",
    "pandas",
    "numpy"
])

# ------------------------------------------------------------
# 2. Locate the repository
#    This works whether Colab opened the repo directly
#    or the repo already exists under /content.
# ------------------------------------------------------------
REPO_ROOT = None

search_roots = [
    Path("/content"),
    Path.cwd()
]

for search_root in search_roots:
    if search_root.exists():
        matches = list(search_root.rglob("capstone.ipynb"))
        for match in matches:
            candidate = match.parent.parent.parent
            if (
                (candidate / "work").exists()
                and (candidate / "submission").exists()
            ):
                REPO_ROOT = candidate
                break
    if REPO_ROOT is not None:
        break

if REPO_ROOT is None:
    raise FileNotFoundError(
        "Repository root could not be located. "
        "Open capstone.ipynb from the GitHub repository in Colab first."
    )

os.chdir(REPO_ROOT)

print("Repository root:", REPO_ROOT)
print("Current working directory:", Path.cwd())

# ------------------------------------------------------------
# 3. Create the required artifact/output directories
# ------------------------------------------------------------
OUTPUT_DIR = REPO_ROOT / "work" / "outputs"
PAPER_DIR = REPO_ROOT / "docs"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PAPER_DIR.mkdir(parents=True, exist_ok=True)

print("Output directory:", OUTPUT_DIR)
print("Paper directory:", PAPER_DIR)

# ------------------------------------------------------------
# 4. Imports
# ------------------------------------------------------------
import duckdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import userdata

from sklearn.model_selection import (
    train_test_split,
    GroupShuffleSplit
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    average_precision_score,
    precision_recall_curve
)

# ------------------------------------------------------------
# 5. Reproducibility
# ------------------------------------------------------------
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# ------------------------------------------------------------
# 6. Hugging Face authentication
#    Token is read from Colab Secrets.
#    Never print or save the token.
# ------------------------------------------------------------
HF_TOKEN = userdata.get("HF_TOKEN")

if not HF_TOKEN:
    raise ValueError(
        "HF_TOKEN was not found in Colab Secrets. "
        "Add HF_TOKEN to Colab Secrets and run this cell again."
    )

# ------------------------------------------------------------
# 7. DuckDB connection
# ------------------------------------------------------------
con = duckdb.connect()

con.execute(f"""
CREATE OR REPLACE SECRET hf_secret (
    TYPE HUGGINGFACE,
    TOKEN '{HF_TOKEN}'
);
""")

print("DuckDB connection: ready")
print("Hugging Face authentication: ready")

# ------------------------------------------------------------
# 8. Project-level constants
# ------------------------------------------------------------
MODEL_MONTH = "2026-03"
FINAL_SEALED_MONTH = "2026-06"

print("Modeling window:", MODEL_MONTH)
print("Final sealed month:", FINAL_SEALED_MONTH)

print("\nSetup completed successfully.")

Repository root: /content/ML_inter_Task1/ML_inter_Task1
Current working directory: /content/ML_inter_Task1/ML_inter_Task1
Output directory: /content/ML_inter_Task1/ML_inter_Task1/work/outputs
Paper directory: /content/ML_inter_Task1/ML_inter_Task1/docs
DuckDB connection: ready
Hugging Face authentication: ready
Modeling window: 2026-03
Final sealed month: 2026-06

Setup completed successfully.


In [ ]:
import os
from pathlib import Path

print("Current directory:")
print(Path.cwd())

print("\nFiles/folders here:")
print(os.listdir())

print("\n/content contents:")
print(os.listdir("/content"))

Current directory:
/content/ML_inter_Task1/ML_inter_Task1

Files/folders here:
['w02_ml_task_framing.ipynb', 'w04_baseline_score.ipynb', 'SETUP.md', 'outputs', 'README.md', '.git', 'submission', 'Copy_of_w07_action_playbook.ipynb', 'GUIDE.md', 'AGENTS.md', '03_working_with_the_full_release.ipynb', 'skills', 'w04_signal_audit.ipynb', 'notebooks', 'DATA_USE.md', '01_first_look_and_discovery.ipynb', '.github', 'data', 'CLAUDE.md', 'requirements.txt', 'work', 'Copy_of_w06_validation_audit.ipynb', 'scripts', 'w03_data_contract.ipynb', 'w01_research_question.ipynb', 'LICENSE', '.gitignore', '02_your_first_readable_model.ipynb', 'docs']

/content contents:
['.config', 'ML_inter_Task1', 'sample_data']


In [ ]:
%cd /content/ML_inter_Task1

import os

print("Current directory:", os.getcwd())
print("\nwork/notebooks:")
print(os.listdir("work/notebooks"))

print("\nsubmission:")
print(os.listdir("submission"))

print("\ndocs:")
print(os.listdir("docs"))

/content/ML_inter_Task1
Current directory: /content/ML_inter_Task1

work/notebooks:
['w02_ml_task_framing.ipynb', 'w06_validation_audit.ipynb', 'w04_baseline_score.ipynb', 'w07_action_playbook.ipynb', 'w05_model.ipynb', 'capstone.ipynb', 'w04_signal_audit.ipynb', 'w03_feature_leakage_check.ipynb', 'w03_data_contract.ipynb', 'w01_research_question.ipynb']

submission:
['README.md', 'paper_url.txt']

docs:
['ml-intern-dataset-and-lane-guide.md', 'ml-core-foundation-framework.md', 'intern-free-tooling-guide.md', 'flyrank-seo-research-march-2026.pdf', 'data-dictionary.md']


In [ ]:
import json
from pathlib import Path

capstone_path = Path("work/notebooks/capstone.ipynb")

with open(capstone_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Notebook found:", capstone_path.exists())
print("Total cells:", len(nb["cells"]))

print("\n--- CAPSTONE SECTIONS ---")

for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "markdown":
        text = "".join(cell["source"]).strip()
        if text:
            print(f"\n[{i}]")
            print(text[:500])

Notebook found: True
Total cells: 16

--- CAPSTONE SECTIONS ---

[0]
# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hibahrehman25-lang/ML_inter_Task1/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment 

[1]
## 1. Question

*The research question and the decision it supports.*

[3]
## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

[5]
## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

[7]
## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

[9]
## 5. Limitations

*What this work cannot cla

In [ ]:
import json
from pathlib import Path

capstone_path = Path("work/notebooks/capstone.ipynb")

with open(capstone_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("CAPSTONE CODE CELLS")
print("=" * 70)

for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code":
        code = "".join(cell["source"]).strip()

        print(f"\n--- CODE CELL {i} ---")

        if code:
            print(code[:3000])
        else:
            print("[EMPTY CODE CELL]")

print("\n" + "=" * 70)
print("Inspection complete.")

CAPSTONE CODE CELLS

--- CODE CELL 2 ---
[EMPTY CODE CELL]

--- CODE CELL 4 ---
[EMPTY CODE CELL]

--- CODE CELL 6 ---
[EMPTY CODE CELL]

--- CODE CELL 8 ---
[EMPTY CODE CELL]

--- CODE CELL 10 ---
[EMPTY CODE CELL]

--- CODE CELL 12 ---
[EMPTY CODE CELL]

--- CODE CELL 14 ---
[EMPTY CODE CELL]

Inspection complete.


In [ ]:
from pathlib import Path

repo = Path("/content/ML_inter_Task1")

print("=== OUTPUTS ===")
outputs = repo / "outputs"

if outputs.exists():
    for p in sorted(outputs.rglob("*")):
        if p.is_file():
            print(p.relative_to(repo))
else:
    print("outputs folder not found")

print("\n=== WORK FILES ===")
work = repo / "work"

for p in sorted(work.rglob("*")):
    if p.is_file():
        print(p.relative_to(repo))

=== OUTPUTS ===
outputs/charts/action_mix.svg
outputs/charts/confidence_mix.svg
outputs/charts/top_feature_importance.svg
outputs/charts/top_reason_codes.svg
outputs/charts/trend_distribution.svg
outputs/model_report.md
outputs/refresh_queue_sample.csv

=== WORK FILES ===
work/README.md
work/capstone_report_template.md
work/notebooks/capstone.ipynb
work/notebooks/w01_research_question.ipynb
work/notebooks/w02_ml_task_framing.ipynb
work/notebooks/w03_data_contract.ipynb
work/notebooks/w03_feature_leakage_check.ipynb
work/notebooks/w04_baseline_score.ipynb
work/notebooks/w04_signal_audit.ipynb
work/notebooks/w05_model.ipynb
work/notebooks/w06_validation_audit.ipynb
work/notebooks/w07_action_playbook.ipynb


In [ ]:
from pathlib import Path

report_path = Path("/content/ML_inter_Task1/outputs/model_report.md")

print("Report exists:", report_path.exists())
print("\n" + "=" * 80)
print("MODEL REPORT")
print("=" * 80)

print(report_path.read_text(encoding="utf-8"))

Report exists: True

MODEL REPORT
# FlyRank Refresh Opportunity Model Report

This report is generated from the bundled anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).
The model ranks existing content for refresh review. It does not use titles, URLs, client names, domains, or keywords.

## Data

- Rows scored: 30,000
- Declining-label rows: 16,262
- Declining-label rate: 0.542
- Split strategy used for validation: client_holdout
- Target: `is_declining_label`

## Model Comparison

Best model: `random_forest` selected by `precision_at_50`.

| Model | ROC AUC | Avg precision | Precision@50 | Recall | F1 |
|---|---:|---:|---:|---:|---:|
| decision_tree | 0.742 | 0.575 | 0.540 | 0.716 | 0.634 |
| logistic_regression | 0.700 | 0.522 | 0.400 | 0.567 | 0.566 |
| random_forest | 0.750 | 0.618 | 0.740 | 0.744 | 0.640 |
| baseline_rules | 0.627 | 0.468 | 0.240 | - | - |

## Final Queue

- High-confidence items: 3,605
- Medium-confidence items: 11,395
- Low-confidence item

## 1. Question

*The research question and the decision it supports.*

## 1. Question

### Research question

Which content pages should be reviewed first because they show observed signals of declining performance or an opportunity for improvement?

### Decision supported

The analysis supports content reviewers and SEO specialists in prioritizing which pages deserve human review first.

### Why this matters

A large content portfolio cannot be reviewed manually with equal attention. The goal is therefore to produce a ranked, decision-support queue that combines multiple observed search and content signals rather than relying on a single threshold.

### Honest framing

This work identifies observed patterns and ranks review opportunities. It does not prove that a recommended content change will cause higher rankings, traffic, CTR, or engagement.

In [ ]:
print("Research question:")
print("Which content pages should be reviewed first based on observed performance signals?")

print("\nDecision:")
print("Prioritize pages for human content review.")

print("\nUse:")
print("Decision-support ranking, not automated publishing.")

Research question:
Which content pages should be reviewed first based on observed performance signals?

Decision:
Prioritize pages for human content review.

Use:
Decision-support ranking, not automated publishing.


## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

## 2. Data

The project uses the FlyRank ML Internship dataset and combines content metadata with observed search-performance signals.

The analysis developed across the internship used anonymized content identifiers and public-safe aggregate fields. No client names, private URLs, raw search queries, or other identifying information are used in the paper.

The initial lane was explored using the anonymized starter dataset containing 30,000 content pages and 44 columns. The later analysis also used the March 2026 performance window for signal validation and opportunity prioritization.

Relevant fields include search impressions, clicks, average search position, CTR, engagement-related measures, content age, word/character counts, content type, intent, and trend signals.

Rows or fields that could expose private information were excluded from the public-facing analysis. The final paper reports aggregate findings and pseudonymized identifiers only.

The resulting queue is a human-review shortlist. It is not an automated content-action system.

In [ ]:
import pandas as pd

starter_path = "data/raw/content_refresh_anonymized.csv"

starter_df = pd.read_csv(starter_path)

print("Starter dataset shape:", starter_df.shape)
print("Rows:", len(starter_df))
print("Columns:", len(starter_df.columns))

print("\nKey fields available:")
key_fields = [
    "search_volume",
    "content_type",
    "main_intent",
    "word_count",
    "char_count",
    "ctr",
    "avg_position",
    "engagement_rate",
    "scroll_rate",
    "trend_direction"
]

print([c for c in key_fields if c in starter_df.columns])

print("\nPublic-safety note:")
print("Analysis uses anonymized/aggregate fields; private client names, URLs, and raw queries are excluded.")

Starter dataset shape: (30000, 44)
Rows: 30000
Columns: 44

Key fields available:
['search_volume', 'content_type', 'main_intent', 'word_count', 'char_count', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'trend_direction']

Public-safety note:
Analysis uses anonymized/aggregate fields; private client names, URLs, and raw queries are excluded.


## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

## 3. Methodology

### Task formulation

The lane is treated as a ranking/opportunity-scoring problem. The objective is to rank content items by review priority rather than produce an automatic publish/no-publish decision.

### Features

The analysis uses observed content and search-performance signals, including impressions, clicks, CTR, average position, engagement-related measures, content age, word/character counts, and related activity signals.

### Label / proxy

For the supervised model evaluation, the target is the defined `is_declining_label` proxy used in the modeling workflow. This represents an observed/rule-defined performance condition rather than a causal outcome.

### Baseline

A rules-based baseline was evaluated against the machine-learning models. The baseline provides a simple reference for determining whether the learned model adds useful ranking performance.

### Models

Decision tree, logistic regression, and random forest models were evaluated. The random forest was selected using Precision@50 because the practical use case is to place valuable review opportunities near the top of the queue.

### Validation

Validation used a client-holdout split so that evaluation was performed on held-out client groups rather than mixing the same client across training and evaluation.

### Leakage checks

The workflow included feature and leakage checks before model interpretation. The goal was to avoid using identifiers, future information, or variables that would make evaluation unrealistically easy.

### Success metric

The primary ranking metric is Precision@50. This directly reflects the practical question: among the first 50 recommended pages, how many correspond to the defined opportunity/declining condition?

In [ ]:
# Evidence from the completed modeling workflow

model_results = pd.DataFrame({
    "model": [
        "decision_tree",
        "logistic_regression",
        "random_forest",
        "baseline_rules"
    ],
    "roc_auc": [0.742, 0.700, 0.750, 0.627],
    "avg_precision": [0.575, 0.522, 0.618, 0.468],
    "precision_at_50": [0.540, 0.400, 0.740, 0.240]
})

print(model_results)

print("\nSelected model: random_forest")
print("Selection metric: Precision@50")
print("Validation strategy: client_holdout")
print("Target: is_declining_label")

                 model  roc_auc  avg_precision  precision_at_50
0        decision_tree    0.742          0.575             0.54
1  logistic_regression    0.700          0.522             0.40
2        random_forest    0.750          0.618             0.74
3       baseline_rules    0.627          0.468             0.24

Selected model: random_forest
Selection metric: Precision@50
Validation strategy: client_holdout
Target: is_declining_label


## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

## 4. Results (vs baseline)

The random forest produced the strongest Precision@50 among the evaluated approaches on the same client-holdout evaluation split.

Precision@50 was 0.740 for the random forest compared with 0.240 for the rules-based baseline. This means the evaluated model placed substantially more defined positive/opportunity cases near the top of the ranking than the baseline on this split.

The random forest also achieved ROC AUC of 0.750 and average precision of 0.618.

These are measured results on the evaluated dataset and split. They should not be interpreted as proof of future production performance or causal improvement in traffic, rankings, CTR, or engagement.

In [ ]:
results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Logistic Regression",
        "Random Forest",
        "Rules Baseline"
    ],
    "ROC AUC": [0.742, 0.700, 0.750, 0.627],
    "Average Precision": [0.575, 0.522, 0.618, 0.468],
    "Precision@50": [0.540, 0.400, 0.740, 0.240]
})

display(results)

rf_p50 = 0.740
baseline_p50 = 0.240

print(f"Random Forest Precision@50: {rf_p50:.3f}")
print(f"Baseline Precision@50: {baseline_p50:.3f}")
print(f"Absolute difference: {rf_p50 - baseline_p50:.3f}")
print(f"Relative multiple: {rf_p50 / baseline_p50:.2f}x")

,Model,ROC AUC,Average Precision,Precision@50
0,Decision Tree,0.742,0.575,0.54
1,Logistic Regression,0.700,0.522,0.40
2,Random Forest,0.750,0.618,0.74
3,Rules Baseline,0.627,0.468,0.24


Random Forest Precision@50: 0.740
Baseline Precision@50: 0.240
Absolute difference: 0.500
Relative multiple: 3.08x


## 5. Limitations

*What this work cannot claim.*

## 5. Limitations

This analysis has several important limitations.

First, the target is a defined observed/rule-based proxy rather than a directly measured business outcome. The model therefore learns the defined evaluation target rather than predicting guaranteed future traffic or revenue.

Second, the evaluation result comes from the available validation design and should not be generalized automatically to every future dataset, client, or time period.

Third, observed associations do not establish causation. A page ranked highly for review may have several possible reasons for its performance, and changing the page is not guaranteed to improve its outcome.

Fourth, the ranked queue is intended for human review. It should not automatically publish, delete, rewrite, or otherwise change content.

Finally, the paper uses anonymized and aggregate information. It deliberately avoids exposing client names, private URLs, or raw queries, which limits the amount of page-specific context that can be shown publicly.

In [ ]:
limitations = [
    "Target is an observed/rule-defined proxy.",
    "Validation results depend on the evaluated split and dataset.",
    "Associations do not establish causation.",
    "Model scores are decision-support signals, not automatic actions.",
    "Public outputs exclude private client, URL, and query information."
]

for i, item in enumerate(limitations, 1):
    print(f"{i}. {item}")

1. Target is an observed/rule-defined proxy.
2. Validation results depend on the evaluated split and dataset.
3. Associations do not establish causation.
4. Model scores are decision-support signals, not automatic actions.
5. Public outputs exclude private client, URL, and query information.


## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

## 6. Ranked recommendations

The model output is converted into a practical human-review playbook.

### 1. Review high-confidence declining/visible opportunities first

Start with pages that combine strong visibility with evidence of declining performance and a high model score. These pages have the clearest observed case for human inspection.

### 2. Review CTR opportunities for visible pages

Pages with meaningful search visibility but comparatively weak CTR should be checked for title/snippet alignment and search-intent fit.

### 3. Review engagement opportunities

Pages showing weak engagement signals should be inspected for content usefulness, structure, readability, and alignment with the visitor's intent.

### 4. Consider expansion only when multiple signals support it

Expansion should not be triggered by one weak metric. It should require supporting evidence across visibility, performance, and content signals.

### 5. Keep monitor items out of automatic action

Lower-confidence items should remain in monitoring rather than being treated as confirmed optimization opportunities.

### Operational rule

The queue is a prioritization aid for human reviewers. A reviewer should inspect the page and its context before taking any content action.

In [ ]:
recommendations = pd.DataFrame({
    "Rank": [1, 2, 3, 4, 5],
    "Recommendation": [
        "Review high-confidence visible declining opportunities",
        "Review visible pages with CTR opportunity",
        "Review pages with engagement opportunity",
        "Consider expansion only with multiple supporting signals",
        "Monitor lower-confidence items"
    ]
})

display(recommendations)

,Rank,Recommendation
0,1,Review high-confidence visible declining oppor...
1,2,Review visible pages with CTR opportunity
2,3,Review pages with engagement opportunity
3,4,Consider expansion only with multiple supporti...
4,5,Monitor lower-confidence items


## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

## 7. Artifacts the paper embeds

The paper uses a small set of charts and tables to make the findings easy to inspect.

The selected artifacts include:

- Model feature importance
- Recommendation/action mix
- Confidence mix
- Top reason codes
- Trend distribution
- Model-versus-baseline performance table

Each chart should communicate one main message and use a short explanatory caption. The artifacts are supporting evidence for the written findings rather than independent claims.

In [ ]:
from pathlib import Path

artifact_paths = [
    "outputs/charts/action_mix.svg",
    "outputs/charts/confidence_mix.svg",
    "outputs/charts/top_feature_importance.svg",
    "outputs/charts/top_reason_codes.svg",
    "outputs/charts/trend_distribution.svg",
]

print("Artifact check:")
for path in artifact_paths:
    exists = Path(path).exists()
    print(f"{path}: {'FOUND' if exists else 'MISSING'}")

Artifact check:
outputs/charts/action_mix.svg: FOUND
outputs/charts/confidence_mix.svg: FOUND
outputs/charts/top_feature_importance.svg: FOUND
outputs/charts/top_reason_codes.svg: FOUND
outputs/charts/trend_distribution.svg: FOUND


## Self-check

Before you submit, confirm each line honestly:

- [✔️] Every section above is filled — markdown thinking AND the code that backs it
- [✔️] The notebook runs top to bottom with no errors (Runtime → Run all)
- [✔️] The notebook runs top to bottom with no errors (Runtime → Run all)
- [✔️] No client names, URLs, or private queries anywhere
- [✔️] My claims use careful words: observed, measured, directional, decision-support
- [✔️] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [✔️] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [✔️] **ML-12 done in this notebook's closing cells:** 5-minute demo outline + a social-post cut + a 3-sentence employer-facing summary.


In [ ]:
!git commit -m "Complete Week 8 capstone paper notebook"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@03a17e30c7a6.(none)')
